language: "en"

pipeline:
- name: "nlp_spacy"
- name: "tokenizer_spacy"
- name: "intent_entity_featurizer_regex"
- name: "intent_featurizer_count_vectors"
- name: "intent_classifier_tensorflow_embedding"
  # nn architecture
  "num_hidden_layers_a": 2
  "hidden_layer_size_a": [256, 256]
  "num_hidden_layers_b": 2
  "hidden_layer_size_b": [256, 256]
  "batch_size": 4
  "epochs": 300
  # embedding parameters
  "embed_dim": 50
  "mu_pos": 0.8  # should be 0.0 < ... < 1.0 for 'cosine'
  "mu_neg": -0.4  # should be -1.0 < ... < 1.0 for 'cosine'
  "similarity_type": "cosine"  # string 'cosine' or 'inner'
  "num_neg": 10
  "use_max_sim_neg": true  # flag which loss function to use
  # regularization
  "C2": 0.002
  "C_emb": 0.8
  "droprate": 0.2
  # flag if to tokenize intents
  intent_tokenization_flag: true
  intent_split_symbol: "+"
  
- name: "ner_crf"
  # features: [["low", "title"], ["bias", "suffix3"], ["upper", "pos", "pos2"]]
  BILOU_flag: true
  max_iterations: 70
  L1_c: 0.1
  L2_c: 0.1

- name: "ner_synonyms"
# - name: "ner_duckling"
  # locale: "en_US"
  # dimensions: ["time"]